In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [3]:
# Read the data into a Pandas DataFrame
Fraud_df = pd.read_excel('Fraud_Database.xlsx')
Fraud_df.head(10)

,first,last,merchant,category,amt,gender,street,city,state,lat,long,city_pop,job,dob,merch_lat,merch_long
0,c51c8bbd9e8c8bc49042ccd5d3e9864d,af71378b7245985acfe79adb3bc39a1a,fraud_Kilback and Sons,entertainment,3.15,M,7683 Natasha Way Apt. 945,Waukesha,WI,42.9993,-88.2196,95015,"Therapist, occupational",1946-01-02,43.042165,-87.428874
1,e1f6a14cd07069692017b53a8ae881f6,e90dfb84e30edf611e326eeb04d680de,fraud_Kuvalis Ltd,gas_transport,73.80,F,2870 Bean Terrace Apt. 756,Thomas,WV,39.1505,-79.5030,836,Forensic psychologist,1981-08-29,39.269038,-79.768206
2,4ffe35db90d94c6041fb8ddf7b44df29,d52e32f3a96a64786814ae9b5279fbe5,fraud_Herzog Ltd,misc_pos,103.95,M,92021 Miranda Meadows,Tamaroa,IL,38.1380,-89.2231,2135,"Development worker, community",1961-01-31,37.588774,-89.212809
3,3e06fa3927cbdf4e9d93ba4541acce86,7930c951e609e461e8226004ed91a985,fraud_Kuphal-Toy,food_dining,37.93,M,539 Underwood Divide,Pea Ridge,AR,36.4539,-94.1180,6434,Product designer,1967-08-28,36.861606,-94.524270
4,2c189daaf59521812364f9c340402b92,febe862bfdffb6fb3a5d38ffb0e09b54,fraud_Bauch-Raynor,grocery_pos,119.95,F,474 Allen Haven,North Loup,NE,41.4972,-98.7858,509,"Nurse, children's",1980-09-15,42.007948,-98.462757
5,604c8dd5066ee30539037569a028dc9b,2042101ac1f6e7741bfe43f3672e6d7c,"fraud_Bernier, Streich and Jewess",grocery_net,53.39,M,39227 Mcpherson Shoals,Lahoma,OK,36.3850,-98.0727,1078,Podiatrist,1989-10-06,36.250587,-97.683559
6,464e07afc9e46359fb480839150595c5,747ce6e1f8581db8800d74ce2ae244b9,fraud_Heaney-Marquardt,entertainment,109.94,M,0638 Fred Ramp Suite 086,Palmdale,CA,34.5715,-118.0231,171170,Chemical engineer,1963-06-04,34.158944,-118.176486
7,472d46cb829018f9dbd65fb8479a49bb,c4163e30f720ca064b8aabf7c95408fb,"fraud_McCullough, Hudson and Schuster",food_dining,97.45,M,6385 Donald Square Suite 429,Springfield,VA,38.8029,-77.2116,104396,Production engineer,1950-11-20,38.324427,-76.547453
8,464e07afc9e46359fb480839150595c5,3882a94c64066370fa15aa4d8fec006b,fraud_Marks Inc,gas_transport,57.09,M,133 Alyssa Plains,Lolita,TX,28.7724,-96.4793,911,Archaeologist,1970-01-18,28.290577,-96.556834
9,4ffe35db90d94c6041fb8ddf7b44df29,2661b408da2bfe8e0e62a16cf42967c3,fraud_Bernhard Inc,gas_transport,80.27,M,3277 Fields Meadows Apt. 790,Greenview,CA,41.5403,-122.9366,308,Call centre manager,1958-09-20,42.116261,-121.966113

In [4]:
# Get a brief summary of the Fraud_info DataFrame.
Fraud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   first       555719 non-null  object
 1   last        555719 non-null  object
 2   merchant    555719 non-null  object
 3   category    555719 non-null  object
 4   amt         555719 non-null  float64
 5   gender      555719 non-null  object
 6   street      555719 non-null  object
 7   city        555719 non-null  object
 8   state       555719 non-null  object
 9   lat         555719 non-null  float64
 10  long        555719 non-null  float64
 11  city_pop    555719 non-null  int64
 12  job         555719 non-null  object
 13  dob         555719 non-null  datetime64[ns]
 14  merch_lat   555719 non-null  float64
 15  merch_long  555719 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 67.8+ MB

In [5]:
# Get the fraud_df columns.
Fraud_df.columns

Index(['first', 'last', 'merchant', 'category', 'amt', 'gender', 'street',
       'city', 'state', 'lat', 'long', 'city_pop', 'job', 'dob', 'merch_lat',
       'merch_long'],
      dtype='object')

In [6]:
# Get the unique categories and subcategories in separate lists.
categories = Fraud_df['category'].unique()
jobs = Fraud_df['job'].unique()
merchant = Fraud_df['merchant'].unique()
city = Fraud_df['city'].unique()
print(categories)
print(jobs)
print(merchant)
print(city)

['entertainment' 'gas_transport' 'misc_pos' 'food_dining' 'grocery_pos'
 'grocery_net' 'shopping_pos' 'misc_net' 'shopping_net' 'home' 'kids_pets'
 'personal_care' 'health_fitness' 'travel']
['Therapist, occupational' 'Forensic psychologist'
 'Development worker, community' 'Product designer' "Nurse, children's"
 'Podiatrist' 'Chemical engineer' 'Production engineer' 'Archaeologist'
 'Call centre manager' 'Sport and exercise psychologist' 'Cytogeneticist'
 'Copy' 'Dealer' 'Systems developer' 'Hospital doctor'
 'Civil engineer, contracting' 'Learning mentor' 'Structural engineer'
 'Clinical biochemist' 'Archivist' 'Scientific laboratory technician'
 'Engineer, land' 'Engineer, petroleum' "Politician's assistant"
 'Geoscientist' 'Teacher, English as a foreign language'
 'Careers information officer' 'Health service manager'
 'Social research officer, government' 'Scientist, research (medical)'
 'Psychologist, sport and exercise' 'Agricultural consultant'
 'Clothing/textile technologist' 'Accountant, chartered certified'
 'Purchasing manager' 'Landscape architect' 'Counselling psychologist'
 'Secondary school teacher' 'Control and instrumentation engineer'
 'Naval architect' 'Occupational hygienist' 'Audiological scientist'
 'Engineer, electronics' 'Petroleum engineer'
 'Research scientist (physical sciences)' 'Drilling engineer'
 'Claims inspector/assessor' 'Radiographer, diagnostic'
 'Psychiatric nurse' 'Diagnostic radiographer' 'Media buyer'
 'Quarry manager' 'Illustrator' 'Chiropodist' 'Occupational psychologist'
 'IT trainer' 'Gaffer' 'Film/video editor' 'Chief of Staff' 'Make'
 "Barrister's clerk" 'Records manager' 'Designer, interior/spatial'
 'Exhibitions officer, museum/gallery' 'Engineer, biomedical'
 'Advice worker' 'Dance movement psychotherapist'
 'Engineer, civil (consulting)' 'Musician' 'Geologist, engineering'
 'Warden/ranger' 'Engineer, automotive' 'Seismic interpreter' 'Osteopath'
 'Plant breeder/geneticist' 'Video editor' 'Designer, textile'
 'Pathologist' 'Community pharmacist' 'Music tutor' 'Arboriculturist'
 'Trading standards officer' 'Bookseller' 'Mudlogger'
 'Medical sales representative' 'Fisheries officer'
 'Industrial/product designer' 'Psychologist, forensic'
 'Teacher, special educational needs' 'Insurance underwriter'
 'Engineer, agricultural' 'Scientist, biomedical' 'Building surveyor'
 'Information systems manager' 'Chartered public finance accountant'
 'Science writer' 'Accounting technician' 'Geochemist' 'Producer, radio'
 'Pharmacologist' 'Lecturer, further education' 'Therapist, sports'
 'Ecologist' 'Heritage manager' 'Race relations officer'
 'Accountant, chartered public finance' 'Surveyor, rural practice'
 'Chief Marketing Officer' 'Physicist, medical'
 'English as a foreign language teacher' 'Exercise physiologist'
 'Field seismologist' 'Immunologist' 'Database administrator'
 'Designer, jewellery' 'Product manager' 'Surveyor, land/geomatics'
 'Broadcast presenter' 'Education officer, museum'
 'Land/geomatics surveyor' 'Radio producer' 'Chartered loss adjuster'
 'Doctor, hospital' 'Location manager' 'Scientist, research (maths)'
 'Chief Operating Officer' 'Copywriter, advertising' 'Statistician'
 'Medical secretary' 'Clinical research associate'
 'Advertising copywriter' 'Engineer, production'
 'Museum/gallery exhibitions officer'
 'Chartered legal executive (England and Wales)' 'Trade mark attorney'
 'Scientist, marine' 'Dispensing optician' 'Engineering geologist'
 'Electrical engineer' 'Chartered accountant' 'Engineer, technical sales'
 'Lexicographer' 'Materials engineer' 'Corporate investment banker'
 'Toxicologist' 'Surveyor, minerals' 'Advertising account executive'
 'Animal nutritionist' 'Physiological scientist' 'Curator'
 'Television/film/video producer' 'English as a second language teacher'
 'Investment banker, corporate' 'Teaching laboratory technician'
 'Public relations account executive' 'Primary school teacher'
 'Colour technologist' 'Community arts worker' 'Radio broadcast assistant'
 'Glass blower/designer' 'Hospital pharmacist' 'Hotel manager'
 'Retail banker' 'Theme park manager' 'Land' 'Exhibition designer'
 'Designer, industrial/product' 'Barrister' 'Barista'
 'Waste management officer' 'Music therapist' 'Leisure centre manager'
 'Librarian, academic' 'Investment analyst' 'Prison officer'
 'Psychotherapist' 'Human resources officer' 'Water engineer'
 'Retail buyer' 'Designer, furniture' 'Child psychotherapist'
 'Magazine features editor' 'Engineer, mining' 'Probation officer'
 'Tourist information centre manager' 'Press photographer'
 'Mechanical engineer' 'Mental health nurse' 'Pensions consultant'
 'Private music teacher' 'Engineer, civil (contracting)'
 'Librarian, public' 'Product/process development scientist' 'Animator'
 'Designer, multimedia' 'Animal technologist' 'Counsellor'
 'Chief Executive Officer' 'Sales executive' 'Cabin crew'
 'Network engineer' 'Production manager' 'Production assistant, radio'
 'Event organiser' 'Secretary/administrator' 'Energy engineer' 'Sub'
 'Television floor manager' 'Scientist, audiological'
 'Further education lecturer' 'Pension scheme manager'
 'Embryologist, clinical' 'Insurance risk surveyor'
 'Therapist, horticultural' 'Surveyor, hydrographic'
 'Engineer, control and instrumentation' 'General practice doctor'
 'Designer, ceramics/pottery' 'Museum/gallery conservator'
 'Research officer, trade union' 'Civil Service administrator'
 'Cartographer' 'Research officer, political party'
 'Arts development officer' 'Acupuncturist' 'Set designer'
 'Geologist, wellsite' 'Therapist, music' 'Phytotherapist'
 'Ceramics designer' 'Emergency planning/management officer'
 'Nurse, mental health' 'Mining engineer' 'Contractor'
 'Building control surveyor' 'Tourism officer' 'Hydrographic surveyor'
 'Armed forces training and education officer' 'Minerals surveyor'
 'Equality and diversity officer' 'Research scientist (medical)'
 'Historic buildings inspector/conservation officer' 'Freight forwarder'
 'Producer, television/film/video' 'Research scientist (life sciences)'
 'Wellsite geologist' 'Energy manager' 'Editor, magazine features'
 'Radiographer, therapeutic' 'Television production assistant'
 'Environmental education officer' 'Commissioning editor'
 'Health and safety adviser' 'Outdoor activities/education manager'
 'Multimedia programmer' 'Community education officer'
 'Environmental health practitioner' 'Chief Financial Officer' 'Architect'
 'Systems analyst' 'Furniture designer' 'Herbalist'
 'Programme researcher, broadcasting/film/video' 'Farm manager'
 'Buyer, industrial' 'Communications engineer' 'Public librarian'
 'Interpreter' 'Horticultural therapist' 'Soil scientist'
 'Financial trader' 'Learning disability nurse' 'Travel agency manager'
 'Health physicist' 'Teacher, early years/pre' 'Art therapist'
 'Psychologist, counselling' 'Theatre manager' 'Equities trader'
 'Aid worker' 'Administrator, arts' 'Geophysicist/field seismologist'
 'Psychotherapist, child' 'Special educational needs teacher'
 'Garment/textile technologist' 'Psychologist, clinical'
 'Scientist, clinical (histocompatibility and immunogenetics)'
 'Operational researcher' 'Press sub' 'Physiotherapist'
 'Financial adviser' 'Manufacturing engineer' 'Art gallery manager'
 'Orthoptist' 'Facilities manager' 'Oceanographer' 'Paramedic'
 'Development worker, international aid' 'Transport planner'
 'Doctor, general practice' 'Applications developer' 'Administrator'
 'TEFL teacher' 'Biomedical scientist' 'Psychiatrist'
 'Educational psychologist' 'Conservator, museum/gallery'
 'Chief Strategy Officer' 'Technical brewer'
 'Conservation officer, historic buildings' 'Tax adviser'
 'Patent attorney' 'Tree surgeon' 'Scientist, physiological'
 'Conservator, furniture' 'Futures trader' 'Amenity horticulturist'
 'Civil Service fast streamer' 'Charity fundraiser'
 'Sales professional, IT' 'Airline pilot'
 'Senior tax professional/tax inspector' 'Licensed conveyancer' 'Surgeon'
 'Market researcher' 'Neurosurgeon' 'Camera operator'
 'Public affairs consultant' 'Engineer, manufacturing' 'Pilot, airline'
 'Programmer, multimedia' 'IT consultant' 'Immigration officer'
 'Editor, commissioning' 'Museum education officer' 'Fine artist'
 'Retail merchandiser' 'Education administrator' 'Pharmacist, community'
 'Textile designer' 'Surveyor, mining' 'Journalist, newspaper'
 'Special effects artist' 'Rural practice surveyor' 'Pharmacist, hospital'
 'Education officer, community' 'Scientist, research (physical sciences)'
 'Volunteer coordinator' 'Maintenance engineer' 'Management consultant'
 'Furniture conservator/restorer' 'Early years teacher'
 'Electronics engineer' 'Quantity surveyor'
 'Logistics and distribution manager' 'Commercial/residential surveyor'
 'Chief Technology Officer' 'Chemist, analytical' 'Marketing executive'
 'Engineer, drilling' 'Commercial horticulturist' 'Insurance broker'
 'Herpetologist' 'Environmental consultant' 'Firefighter' 'Economist'
 'Tour manager' 'Health promotion specialist' 'Theatre director'
 'Editor, film/video' 'Teacher, primary school'
 'Regulatory affairs officer' 'Designer, exhibition/display'
 'Teacher, secondary school' 'Sports development officer'
 'Charity officer' 'Tax inspector' 'Police officer' 'Biochemist, clinical'
 'Engineer, aeronautical' 'Programmer, applications'
 'Clinical cytogeneticist' 'Water quality scientist'
 'Public house manager' 'Administrator, education' 'Engineer, maintenance'
 'Social researcher' 'Lawyer' 'Company secretary' 'Health visitor'
 'Research scientist (maths)' 'Sports administrator'
 'Aeronautical engineer' 'Nutritional therapist'
 'Engineer, broadcasting (operations)' 'Associate Professor'
 'Field trials officer' 'Town planner' 'Optometrist' 'Academic librarian'
 'Site engineer' 'Lecturer, higher education' 'Clinical psychologist'
 'Comptroller' 'Local government officer' 'Advertising account planner'
 'Risk analyst' 'Web designer' 'Investment banker, operational'
 'Armed forces logistics/support/administrative officer' 'Artist'
 'Administrator, local government' 'Occupational therapist'
 'Data scientist' 'Visual merchandiser' 'Restaurant manager, fast food'
 'Catering manager' 'Operations geologist'
 'Planning and development surveyor'
 'Administrator, charities/voluntary organisations'
 'Horticultural consultant' 'Engineer, communications'
 'Community development worker' 'Manufacturing systems engineer'
 'Higher education careers adviser' 'Merchandiser, retail'
 'Biomedical engineer' 'Nature conservation officer'
 'Horticulturist, commercial' 'Interior and spatial designer'
 'Therapist, drama' 'Metallurgist' 'Teacher, adult education'
 'Loss adjuster, chartered' 'Engineer, building services'
 'Building services engineer' 'Intelligence analyst'
 'Optician, dispensing' 'Therapist, art' 'Estate manager/land agent'
 'Hydrologist' 'Medical physicist' 'Hydrogeologist'
 'Training and development officer' 'Presenter, broadcasting'
 'Geneticist, molecular' 'Air broker' 'Insurance claims handler'
 'Engineer, structural' 'Fitness centre manager'
 'Architectural technologist' 'Retail manager'
 'Designer, television/film set' 'Telecommunications researcher'
 'Jewellery designer' 'Environmental manager' 'Paediatric nurse'
 'Oncologist' 'Solicitor, Scotland' 'Magazine journalist'
 'Ambulance person' 'Stage manager' 'Writer' 'Analytical chemist'
 'Medical technical officer' 'Media planner' 'Professor Emeritus'
 'Air cabin crew' 'Buyer, retail' 'Television camera operator'
 'Public relations officer' 'Broadcast engineer'
 'Production assistant, television' 'Engineer, materials'
 'Operational investment banker' 'Software engineer' 'Engineer, water']
['fraud_Kilback and Sons' 'fraud_Kuvalis Ltd' 'fraud_Herzog Ltd'
 'fraud_Kuphal-Toy' 'fraud_Bauch-Raynor'
 'fraud_Bernier, Streich and Jewess' 'fraud_Heaney-Marquardt'
 'fraud_McCullough, Hudson and Schuster' 'fraud_Marks Inc'
 'fraud_Bernhard Inc' 'fraud_Kohler, Lindgren and Koelpin'
 'fraud_Heller-Langosh' 'fraud_Johns Inc' 'fraud_Towne LLC'
 'fraud_Willms, Kris and Bergnaum' 'fraud_Thiel-Thiel' 'fraud_Mante Group'
 "fraud_Deckow-O'Conner" 'fraud_Bruen-Yost' 'fraud_Jaskolski-Dibbert'
 'fraud_Pacocha-Bauch' 'fraud_Predovic Inc' 'fraud_Harber Inc'
 'fraud_Morissette LLC' 'fraud_Connelly, Reichert and Fritsch'
 'fraud_Corwin-Collins' 'fraud_Roob LLC' 'fraud_Schmitt Inc'
 'fraud_Robel, Cummerata and Prosacco' 'fraud_Miller-Hauck'
 'fraud_Cummings LLC' 'fraud_Balistreri-Nader' 'fraud_Kiehn Inc'
 'fraud_Jones, Sawayn and Romaguera' 'fraud_Ankunding LLC'
 'fraud_Kilback Group' 'fraud_Schoen, Kuphal and Nitzsche'
 'fraud_Sporer Inc' 'fraud_Osinski, Ledner and Leuschke'
 'fraud_Goldner, Kovacek and Abbott' 'fraud_Donnelly LLC'
 'fraud_Baumbach, Strosin and Nicolas' 'fraud_Emard Inc'
 'fraud_Stroman, Hudson and Erdman' 'fraud_Rau and Sons'
 'fraud_Terry, Johns and Bins' 'fraud_Stokes, Christiansen and Sipes'
 'fraud_Huels-Hahn' 'fraud_Funk Group' 'fraud_Padberg-Rogahn'
 'fraud_Schaefer, McGlynn and Bosco' 'fraud_Morissette PLC'
 'fraud_Rowe, Batz and Goodwin' 'fraud_Kerluke, Considine and Macejkovic'
 'fraud_Stamm-Rodriguez' 'fraud_Armstrong, Walter and Gottlieb'
 'fraud_Rodriguez Group' 'fraud_Conroy-Cruickshank'
 'fraud_Olson, Becker and Koch' 'fraud_Luettgen PLC' 'fraud_Kutch-Hegmann'
 'fraud_Thiel PLC' 'fraud_Swaniawski, Bahringer and Ledner'
 'fraud_Bogisich-Homenick' 'fraud_Bartoletti-Wunsch'
 'fraud_Mosciski, Ziemann and Farrell' 'fraud_Hudson-Ratke'
 'fraud_Kling Inc' 'fraud_Wilkinson Ltd' 'fraud_Reilly, Heaney and Cole'
 'fraud_Johnson, Runolfsdottir and Mayer' 'fraud_Smith-Stokes'
 'fraud_Kassulke PLC' 'fraud_Welch Inc'
 'fraud_Langosh, Wintheiser and Hyatt' 'fraud_Stiedemann Inc'
 "fraud_O'Keefe-Hudson" 'fraud_Bins, Balistreri and Beatty'
 'fraud_Ledner-Pfannerstill' 'fraud_Rempel PLC' 'fraud_Schmidt and Sons'
 'fraud_Raynor, Feest and Miller'
 'fraud_Parisian, Schiller and Altenwerth' 'fraud_Wisozk and Sons'
 'fraud_Cummerata-Jones' 'fraud_Heller-Abshire'
 'fraud_Kutch, Hermiston and Farrell' "fraud_Friesen-D'Amore"
 'fraud_Dach-Nader' 'fraud_Koepp-Parker' 'fraud_Doyle Ltd'
 'fraud_Huels-Nolan' 'fraud_Huel Ltd' 'fraud_McDermott-Rice'
 'fraud_Harris, Gusikowski and Heaney' 'fraud_Lebsack and Sons'
 'fraud_Turner and Sons' 'fraud_Lockman Ltd'
 'fraud_Herman, Treutel and Dickens' 'fraud_Erdman-Kertzmann'
 'fraud_Williamson LLC' 'fraud_Douglas-White' 'fraud_Hermann and Sons'
 'fraud_Jenkins, Hauck and Friesen' 'fraud_Block Group'
 'fraud_Koss and Sons' 'fraud_Corwin-Gorczany' 'fraud_Flatley-Durgan'
 'fraud_Hickle Group' 'fraud_Harris Inc' 'fraud_Bins-Rice'
 'fraud_Smitham-Schiller' 'fraud_Heathcote, Yost and Kertzmann'
 'fraud_Murray Ltd' 'fraud_Wuckert-Walter'
 'fraud_Schultz, Simonis and Little' 'fraud_Rutherford-Mertz'
 'fraud_Strosin-Cruickshank' 'fraud_Macejkovic-Lesch'
 'fraud_Skiles-Ankunding' 'fraud_Gibson-Deckow' 'fraud_Kunze Inc'
 'fraud_Howe PLC' 'fraud_Towne, Greenholt and Koepp'
 'fraud_Parisian and Sons' 'fraud_Reichel Inc'
 'fraud_Lind, Huel and McClure' 'fraud_Cartwright-Harris'
 'fraud_Gleason-Macejkovic' 'fraud_Hayes, Marquardt and Dibbert'
 'fraud_Wolf Inc' 'fraud_Zieme, Bode and Dooley' 'fraud_Rowe-Vandervort'
 'fraud_Simonis-Prohaska' 'fraud_Nader-Heller'
 'fraud_Towne, Walker and Borer' 'fraud_Kovacek, Dibbert and Ondricka'
 'fraud_Goyette Inc' 'fraud_Kuhic Inc' 'fraud_Volkman Ltd'
 'fraud_Padberg-Welch' 'fraud_Eichmann, Bogan and Rodriguez'
 'fraud_Friesen-Stamm' 'fraud_Raynor, Reinger and Hagenes'
 'fraud_Hintz-Bruen' 'fraud_Maggio-Fahey' 'fraud_Boyer-Reichert'
 "fraud_O'Keefe-Wisoky" 'fraud_Runolfsson and Sons'
 'fraud_Heller, Gutmann and Zieme' 'fraud_Murray-Smitham'
 'fraud_Schumm, Bauch and Ondricka' 'fraud_Haley, Jewess and Bechtelar'
 'fraud_Kunde-Sanford' 'fraud_Lehner, Mosciski and King'
 'fraud_Greenfelder, Bartoletti and Davis' 'fraud_Mraz-Herzog'
 'fraud_Dickinson Ltd' 'fraud_Parker, Nolan and Trantow'
 'fraud_Bailey-Morar' 'fraud_Zemlak Group' 'fraud_Emmerich-Luettgen'
 'fraud_Kiehn-Emmerich' 'fraud_Douglas, Schneider and Turner'
 'fraud_Reichert, Huels and Hoppe' 'fraud_Mosciski, Gislason and Mertz'
 'fraud_DuBuque LLC' 'fraud_Nienow, Ankunding and Collier'
 'fraud_Adams, Kovacek and Kuhlman' 'fraud_Kris-Padberg'
 'fraud_Streich, Hansen and Veum' 'fraud_Price Inc'
 'fraud_Brekke and Sons' 'fraud_Beier LLC' 'fraud_Bradtke PLC'
 'fraud_Wiza LLC' 'fraud_Ruecker Group' 'fraud_Heidenreich PLC'
 'fraud_McGlynn-Jaskolski' 'fraud_Kuhn LLC' 'fraud_VonRueden Group'
 'fraud_Cremin, Hamill and Reichel' 'fraud_Miller-Harris'
 'fraud_Vandervort-Funk' 'fraud_Pfeffer and Sons' 'fraud_Barrows PLC'
 'fraud_Moen, Reinger and Murphy' 'fraud_Fisher Inc' 'fraud_Mayert Group'
 'fraud_Hackett-Lueilwitz' 'fraud_McDermott-Weimann' 'fraud_Conroy Ltd'
 'fraud_Greenholt, Jacobi and Gleason' 'fraud_Kemmer-Reinger'
 'fraud_Huel, Hammes and Witting' "fraud_Greenholt, O'Hara and Balistreri"
 'fraud_Hermiston, Russel and Price' 'fraud_Kemmer-Buckridge'
 'fraud_Hamill-Daugherty' 'fraud_Cummerata-Hilpert'
 'fraud_McCullough Group' 'fraud_Mohr-Bayer' 'fraud_Goodwin-Nitzsche'
 'fraud_Schulist Ltd' 'fraud_Flatley Group' 'fraud_Kutch Group'
 'fraud_Dicki Ltd' 'fraud_Schuppe LLC' 'fraud_Wiegand-Lowe'
 'fraud_Christiansen, Goyette and Schamberger'
 'fraud_Jaskolski-Vandervort' 'fraud_Torphy-Goyette'
 "fraud_O'Hara-Wilderman" 'fraud_Lockman, West and Runte'
 'fraud_Lehner, Reichert and Mills' 'fraud_Reynolds-Schinner'
 'fraud_Johnston, Nikolaus and Maggio' 'fraud_Dickinson-Rempel'
 'fraud_Barton Inc' 'fraud_Reilly LLC' 'fraud_Labadie, Treutel and Bode'
 'fraud_Monahan, Bogisich and Ledner' 'fraud_Huel-Langworth'
 'fraud_Streich, Dietrich and Barton' 'fraud_Johns-Hoeger'
 'fraud_Schmeler Inc' 'fraud_Torp-Labadie'
 'fraud_Ferry, Lynch and Kautzer' 'fraud_McCullough LLC'
 'fraud_Auer-Mosciski' 'fraud_Romaguera, Cruickshank and Greenholt'
 'fraud_Nicolas, Hills and McGlynn' 'fraud_Buckridge PLC'
 'fraud_Keeling-Crist' 'fraud_Wintheiser, Dietrich and Schimmel'
 'fraud_McGlynn-Heathcote' 'fraud_Cole PLC'
 'fraud_Bernhard, Grant and Langworth' 'fraud_Morar Inc'
 'fraud_Yost, Block and Koepp' 'fraud_Kuphal-Bartoletti'
 'fraud_Schaefer, Maggio and Daugherty' 'fraud_Denesik and Sons'
 'fraud_Spinka-Welch' 'fraud_Leannon-Ward' 'fraud_Kuhic LLC'
 'fraud_Halvorson Group' 'fraud_Gerlach Inc'
 'fraud_Effertz, Welch and Schowalter' 'fraud_Kihn Inc'
 'fraud_Quitzon, Green and Bashirian' 'fraud_Durgan-Auer'
 'fraud_Pouros-Haag' 'fraud_Gutmann Ltd' 'fraud_Tromp, Kerluke and Glover'
 'fraud_Morissette, Weber and Wiegand' 'fraud_Jacobi and Sons'
 'fraud_Donnelly PLC' 'fraud_Kozey-Boehm' 'fraud_Stamm-Witting'
 'fraud_Dach-Borer' 'fraud_Pagac LLC' 'fraud_Kutch LLC'
 'fraud_Tillman, Fritsch and Schmitt'
 'fraud_Tillman, Dickinson and Labadie' 'fraud_Goldner-Lemke'
 'fraud_Kutch and Sons' 'fraud_Jast Ltd' 'fraud_Pouros-Conroy'
 'fraud_Berge LLC' 'fraud_Kihn, Abernathy and Douglas'
 'fraud_Stracke-Lemke' 'fraud_Rodriguez, Yost and Jenkins'
 'fraud_Rippin, Kub and Mann' 'fraud_Casper, Hand and Zulauf'
 "fraud_Pacocha-O'Reilly" 'fraud_Goyette, Howell and Collier'
 'fraud_Klein Group' 'fraud_Gislason Group' 'fraud_Medhurst PLC'
 'fraud_Spencer-Runolfsson' 'fraud_Rempel Inc'
 'fraud_Bernier, Volkman and Hoeger'
 'fraud_Langworth, Boehm and Gulgowski' 'fraud_Cruickshank-Mills'
 'fraud_Koepp-Witting' 'fraud_Kerluke, Kertzmann and Wiza'
 'fraud_Hermann-Gaylord' 'fraud_Pfeffer LLC'
 'fraud_Baumbach, Feeney and Morar' 'fraud_Fadel, Mertz and Rippin'
 'fraud_Dibbert and Sons' 'fraud_Sawayn PLC' 'fraud_Bogisich Inc'
 'fraud_Schmitt Ltd' "fraud_Schamberger-O'Keefe"
 'fraud_Wiza, Schaden and Stark' 'fraud_Dooley-Thompson'
 'fraud_Kling-Grant' 'fraud_Beier-Hyatt' 'fraud_Howe Ltd'
 'fraud_Fisher-Schowalter' 'fraud_Bednar Group'
 'fraud_Reichert, Shanahan and Hayes'
 'fraud_Bahringer, Schoen and Corkery' 'fraud_Koss, McLaughlin and Mayer'
 'fraud_Turcotte, McKenzie and Koss' 'fraud_Schmeler, Bashirian and Price'
 'fraud_Roob, Conn and Tremblay' 'fraud_Grimes LLC' 'fraud_Kerluke PLC'

In [7]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(categories))
print(len(jobs))
print(len(merchant))
print(len(city))

14
478
693
849

In [8]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 15)
job_ids = np.arange(1, 479)
merchant_ids = np.arange(1, 694)
city_ids = np.arange(1, 850)

print(category_ids)
print(job_ids)
print(merchant_ids)
print(city_ids)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702
 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738
 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774
 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792
 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810
 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828
 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846
 847 848 849]

In [9]:
# Use a list comprehension to add "cat" to each category_id. 
cat_ids = [f"cat{category_id}" for category_id in category_ids]
# Use a list comprehension to add "job" to each job_id.    
job_ids = [f"job{job_id}" for job_id in job_ids]
# Use a list comprehension to add "merchant" to each merchant_id.    
merchant_ids = [f"merchant{merchant_id}" for merchant_id in merchant_ids]
# Use a list comprehension to add "city" to each city_id.    
city_ids = [f"city{city_id}" for city_id in city_ids]
    
print(cat_ids)
print(job_ids)
print(merchant_ids)
print(city_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14']
['job1', 'job2', 'job3', 'job4', 'job5', 'job6', 'job7', 'job8', 'job9', 'job10', 'job11', 'job12', 'job13', 'job14', 'job15', 'job16', 'job17', 'job18', 'job19', 'job20', 'job21', 'job22', 'job23', 'job24', 'job25', 'job26', 'job27', 'job28', 'job29', 'job30', 'job31', 'job32', 'job33', 'job34', 'job35', 'job36', 'job37', 'job38', 'job39', 'job40', 'job41', 'job42', 'job43', 'job44', 'job45', 'job46', 'job47', 'job48', 'job49', 'job50', 'job51', 'job52', 'job53', 'job54', 'job55', 'job56', 'job57', 'job58', 'job59', 'job60', 'job61', 'job62', 'job63', 'job64', 'job65', 'job66', 'job67', 'job68', 'job69', 'job70', 'job71', 'job72', 'job73', 'job74', 'job75', 'job76', 'job77', 'job78', 'job79', 'job80', 'job81', 'job82', 'job83', 'job84', 'job85', 'job86', 'job87', 'job88', 'job89', 'job90', 'job91', 'job92', 'job93', 'job94', 'job95', 'job96', 'job97', 'job98', 'job99', 'job100', 'job101', 'job102', 'job103', 'job104', 'job105', 'job106', 'job107', 'job108', 'job109', 'job110', 'job111', 'job112', 'job113', 'job114', 'job115', 'job116', 'job117', 'job118', 'job119', 'job120', 'job121', 'job122', 'job123', 'job124', 'job125', 'job126', 'job127', 'job128', 'job129', 'job130', 'job131', 'job132', 'job133', 'job134', 'job135', 'job136', 'job137', 'job138', 'job139', 'job140', 'job141', 'job142', 'job143', 'job144', 'job145', 'job146', 'job147', 'job148', 'job149', 'job150', 'job151', 'job152', 'job153', 'job154', 'job155', 'job156', 'job157', 'job158', 'job159', 'job160', 'job161', 'job162', 'job163', 'job164', 'job165', 'job166', 'job167', 'job168', 'job169', 'job170', 'job171', 'job172', 'job173', 'job174', 'job175', 'job176', 'job177', 'job178', 'job179', 'job180', 'job181', 'job182', 'job183', 'job184', 'job185', 'job186', 'job187', 'job188', 'job189', 'job190', 'job191', 'job192', 'job193', 'job194', 'job195', 'job196', 'job197', 'job198', 'job199', 'job200', 'job201', 'job202', 'job203', 'job204', 'job205', 'job206', 'job207', 'job208', 'job209', 'job210', 'job211', 'job212', 'job213', 'job214', 'job215', 'job216', 'job217', 'job218', 'job219', 'job220', 'job221', 'job222', 'job223', 'job224', 'job225', 'job226', 'job227', 'job228', 'job229', 'job230', 'job231', 'job232', 'job233', 'job234', 'job235', 'job236', 'job237', 'job238', 'job239', 'job240', 'job241', 'job242', 'job243', 'job244', 'job245', 'job246', 'job247', 'job248', 'job249', 'job250', 'job251', 'job252', 'job253', 'job254', 'job255', 'job256', 'job257', 'job258', 'job259', 'job260', 'job261', 'job262', 'job263', 'job264', 'job265', 'job266', 'job267', 'job268', 'job269', 'job270', 'job271', 'job272', 'job273', 'job274', 'job275', 'job276', 'job277', 'job278', 'job279', 'job280', 'job281', 'job282', 'job283', 'job284', 'job285', 'job286', 'job287', 'job288', 'job289', 'job290', 'job291', 'job292', 'job293', 'job294', 'job295', 'job296', 'job297', 'job298', 'job299', 'job300', 'job301', 'job302', 'job303', 'job304', 'job305', 'job306', 'job307', 'job308', 'job309', 'job310', 'job311', 'job312', 'job313', 'job314', 'job315', 'job316', 'job317', 'job318', 'job319', 'job320', 'job321', 'job322', 'job323', 'job324', 'job325', 'job326', 'job327', 'job328', 'job329', 'job330', 'job331', 'job332', 'job333', 'job334', 'job335', 'job336', 'job337', 'job338', 'job339', 'job340', 'job341', 'job342', 'job343', 'job344', 'job345', 'job346', 'job347', 'job348', 'job349', 'job350', 'job351', 'job352', 'job353', 'job354', 'job355', 'job356', 'job357', 'job358', 'job359', 'job360', 'job361', 'job362', 'job363', 'job364', 'job365', 'job366', 'job367', 'job368', 'job369', 'job370', 'job371', 'job372', 'job373', 'job374', 'job375', 'job376', 'job377', 'job378', 'job379', 'job380', 'job381', 'job382', 'job383', 'job384', 'job385', 'job386', 'job387', 'job388', 'job389', 'job390', 'job391', 'job392', 'job393', 'job394', 'job395', 'job396', 'job397', 'job398', 'job399', 'job400', 'job401', 'job402', 'job403', 'job404', 'job405', 'job406', 'job407', 'job408', 'job409', 'job410', 'job411', 'job412', 'job413', 'job414', 'job415', 'job416', 'job417', 'job418', 'job419', 'job420', 'job421', 'job422', 'job423', 'job424', 'job425', 'job426', 'job427', 'job428', 'job429', 'job430', 'job431', 'job432', 'job433', 'job434', 'job435', 'job436', 'job437', 'job438', 'job439', 'job440', 'job441', 'job442', 'job443', 'job444', 'job445', 'job446', 'job447', 'job448', 'job449', 'job450', 'job451', 'job452', 'job453', 'job454', 'job455', 'job456', 'job457', 'job458', 'job459', 'job460', 'job461', 'job462', 'job463', 'job464', 'job465', 'job466', 'job467', 'job468', 'job469', 'job470', 'job471', 'job472', 'job473', 'job474', 'job475', 'job476', 'job477', 'job478']
['merchant1', 'merchant2', 'merchant3', 'merchant4', 'merchant5', 'merchant6', 'merchant7', 'merchant8', 'merchant9', 'merchant10', 'merchant11', 'merchant12', 'merchant13', 'merchant14', 'merchant15', 'merchant16', 'merchant17', 'merchant18', 'merchant19', 'merchant20', 'merchant21', 'merchant22', 'merchant23', 'merchant24', 'merchant25', 'merchant26', 'merchant27', 'merchant28', 'merchant29', 'merchant30', 'merchant31', 'merchant32', 'merchant33', 'merchant34', 'merchant35', 'merchant36', 'merchant37', 'merchant38', 'merchant39', 'merchant40', 'merchant41', 'merchant42', 'merchant43', 'merchant44', 'merchant45', 'merchant46', 'merchant47', 'merchant48', 'merchant49', 'merchant50', 'merchant51', 'merchant52', 'merchant53', 'merchant54', 'merchant55', 'merchant56', 'merchant57', 'merchant58', 'merchant59', 'merchant60', 'merchant61', 'merchant62', 'merchant63', 'merchant64', 'merchant65', 'merchant66', 'merchant67', 'merchant68', 'merchant69', 'merchant70', 'merchant71', 'merchant72', 'merchant73', 'merchant74', 'merchant75', 'merchant76', 'merchant77', 'merchant78', 'merchant79', 'merchant80', 'merchant81', 'merchant82', 'merchant83', 'merchant84', 'merchant85', 'merchant86', 'merchant87', 'merchant88', 'merchant89', 'merchant90', 'merchant91', 'merchant92', 'merchant93', 'merchant94', 'merchant95', 'merchant96', 'merchant97', 'merchant98', 'merchant99', 'merchant100', 'merchant101', 'merchant102', 'merchant103', 'merchant104', 'merchant105', 'merchant106', 'merchant107', 'merchant108', 'merchant109', 'merchant110', 'merchant111', 'merchant112', 'merchant113', 'merchant114', 'merchant115', 'merchant116', 'merchant117', 'merchant118', 'merchant119', 'merchant120', 'merchant121', 'merchant122', 'merchant123', 'merchant124', 'merchant125', 'merchant126', 'merchant127', 'merchant128', 'merchant129', 'merchant130', 'merchant131', 'merchant132', 'merchant133', 'merchant134', 'merchant135', 'merchant136', 'merchant137', 'merchant138', 'merchant139', 'merchant140', 'merchant141', 'merchant142', 'merchant143', 'merchant144', 'merchant145', 'merchant146', 'merchant147', 'merchant148', 'merchant149', 'merchant150', 'merchant151', 'merchant152', 'merchant153', 'merchant154', 'merchant155', 'merchant156', 'merchant157', 'merchant158', 'merchant159', 'merchant160', 'merchant161', 'merchant162', 'merchant163', 'merchant164', 'merchant165', 'merchant166', 'merchant167', 'merchant168', 'merchant169', 'merchant170', 'merchant171', 'merchant172', 'merchant173', 'merchant174', 'merchant175', 'merchant176', 'merchant177', 'merchant178', 'merchant179', 'merchant180', 'merchant181', 'merchant182', 'merchant183', 'merchant184', 'merchant185', 'merchant186', 'merchant187', 'merchant188', 'merchant189', 'merchant190', 'merchant191', 'merchant192', 'merchant193', 'merchant194', 'merchant195', 'merchant196', 'merchant197', 'merchant198', 'merchant199', 'merchant200', 'merchant201', 'merchant202', 'merchant203', 'merchant204', 'merchant205', 'merchant206', 'merchant207', 'merchant208', 'merchant209', 'merchant210', 'merchant211', 'merchant212', 'merchant213', 'merchant214', 'merchant215', 'merchant216', 'merchant217', 'merchant218', 'merchant219', 'merchant220', 'merchant221', 'merchant222', 'merchant223', 'merchant224', 'merchant225', 'merchant226', 'merchant227', 'merchant228', 'merchant229', 'merchant230', 'merchant231', 'merchant232', 'merchant233', 'merchant234', 'merchant235', 'merchant236', 'merchant237', 'merchant238', 'merchant239', 'merchant240', 'merchant241', 'merchant242', 'merchant243', 'merchant244', 'merchant245', 'merchant246', 'merchant247', 'merchant248', 'merchant249', 'merchant250', 'merchant251', 'merchant252', 'merchant253', 'merchant254', 'merchant255', 'merchant256', 'merchant257', 'merchant258', 'merchant259', 'merchant260', 'merchant261', 'merchant262', 'merchant263', 'merchant264', 'merchant265', 'merchant266', 'merchant267', 'merchant268', 'merchant269', 'merchant270', 'merchant271', 'merchant272', 'merchant273', 'merchant274', 'merchant275', 'merchant276', 'merchant277', 'merchant278', 'merchant279', 'merchant280', 'merchant281', 'merchant282', 'merchant283', 'merchant284', 'merchant285', 'merchant286', 'merchant287', 'merchant288', 'merchant289', 'merchant290', 'merchant291', 'merchant292', 'merchant293', 'merchant294', 'merchant295', 'merchant296', 'merchant297', 'merchant298', 'merchant299', 'merchant300', 'merchant301', 'merchant302', 'merchant303', 'merchant304', 'merchant305', 'merchant306', 'merchant307', 'merchant308', 'merchant309', 'merchant310', 'merchant311', 'merchant312', 'merchant313', 'merchant314', 'merchant315', 'merchant316', 'merchant317', 'merchant318', 'merchant319', 'merchant320', 'merchant321', 'merchant322', 'merchant323', 'merchant324', 'merchant325', 'merchant326', 'merchant327', 'merchant328', 'merchant329', 'merchant330', 'merchant331', 'merchant332', 'merchant333', 'merchant334', 'merchant335', 'merchant336', 'merchant337', 'merchant338', 'merchant339', 'merchant340', 'merchant341', 'merchant342', 'merchant343', 'merchant344', 'merchant345', 'merchant346', 'merchant347', 'merchant348', 'merchant349', 'merchant350', 'merchant351', 'merchant352', 'merchant353', 'merchant354', 'merchant355', 'merchant356', 'merchant357', 'merchant358', 'merchant359', 'merchant360', 'merchant361', 'merchant362', 'merchant363', 'merchant364', 'merchant365', 'merchant366', 'merchant367', 'merchant368', 'merchant369', 'merchant370', 'merchant371', 'merchant372', 'merchant373', 'merchant374', 'merchant375', 'merchant376', 'merchant377', 'merchant378', 'merchant379', 'merchant380', 'merchant381', 'merchant382', 'merchant383', 'merchant384', 'merchant385', 'merchant386', 'merchant387', 'merchant388', 'merchant389', 'merchant390', 'merchant391', 'merchant392', 'merchant393', 'merchant394', 'merchant395', 'merchant396', 'merchant397', 'merchant398', 'merchant399', 'merchant400', 'merchant401', 'merchant402', 'merchant403', 'merchant404', 'merchant405', 'merchant406', 'merchant407', 'merchant408', 'merchant409', 'merchant410', 'merchant411', 'merchant412', 'merchant413', 'merchant414', 'merchant415', 'merchant416', 'merchant417', 'merchant418', 'merchant419', 'merchant420', 'merchant421', 'merchant422', 'merchant423', 'merchant424', 'merchant425', 'merchant426', 'merchant427', 'merchant428', 'merchant429', 'merchant430', 'merchant431', 'merchant432', 'merchant433', 'merchant434', 'merchant435', 'merchant436', 'merchant437', 'merchant438', 'merchant439', 'merchant440', 'merchant441', 'merchant442', 'merchant443', 'merchant444', 'merchant445', 'merchant446', 'merchant447', 'merchant448', 'merchant449', 'merchant450', 'merchant451', 'merchant452', 'merchant453', 'merchant454', 'merchant455', 'merchant456', 'merchant457', 'merchant458', 'merchant459', 'merchant460', 'merchant461', 'merchant462', 'merchant463', 'merchant464', 'merchant465', 'merchant466', 'merchant467', 'merchant468', 'merchant469', 'merchant470', 'merchant471', 'merchant472', 'merchant473', 'merchant474', 'merchant475', 'merchant476', 'merchant477', 'merchant478', 'merchant479', 'merchant480', 'merchant481', 'merchant482', 'merchant483', 'merchant484', 'merchant485', 'merchant486', 'merchant487', 'merchant488', 'merchant489', 'merchant490', 'merchant491', 'merchant492', 'merchant493', 'merchant494', 'merchant495', 'merchant496', 'merchant497', 'merchant498', 'merchant499', 'merchant500', 'merchant501', 'merchant502', 'merchant503', 'merchant504', 'merchant505', 'merchant506', 'merchant507', 'merchant508', 'merchant509', 'merchant510', 'merchant511', 'merchant512', 'merchant513', 'merchant514', 'merchant515', 'merchant516', 'merchant517', 'merchant518', 'merchant519', 'merchant520', 'merchant521', 'merchant522', 'merchant523', 'merchant524', 'merchant525', 'merchant526', 'merchant527', 'merchant528', 'merchant529', 'merchant530', 'merchant531', 'merchant532', 'merchant533', 'merchant534', 'merchant535', 'merchant536', 'merchant537', 'merchant538', 'merchant539', 'merchant540', 'merchant541', 'merchant542', 'merchant543', 'merchant544', 'merchant545', 'merchant546', 'merchant547', 'merchant548', 'merchant549', 'merchant550', 'merchant551', 'merchant552', 'merchant553', 'merchant554', 'merchant555', 'merchant556', 'merchant557', 'merchant558', 'merchant559', 'merchant560', 'merchant561', 'merchant562', 'merchant563', 'merchant564', 'merchant565', 'merchant566', 'merchant567', 'merchant568', 'merchant569', 'merchant570', 'merchant571', 'merchant572', 'merchant573', 'merchant574', 'merchant575', 'merchant576', 'merchant577', 'merchant578', 'merchant579', 'merchant580', 'merchant581', 'merchant582', 'merchant583', 'merchant584', 'merchant585', 'merchant586', 'merchant587', 'merchant588', 'merchant589', 'merchant590', 'merchant591', 'merchant592', 'merchant593', 'merchant594', 'merchant595', 'merchant596', 'merchant597', 'merchant598', 'merchant599', 'merchant600', 'merchant601', 'merchant602', 'merchant603', 'merchant604', 'merchant605', 'merchant606', 'merchant607', 'merchant608', 'merchant609', 'merchant610', 'merchant611', 'merchant612', 'merchant613', 'merchant614', 'merchant615', 'merchant616', 'merchant617', 'merchant618', 'merchant619', 'merchant620', 'merchant621', 'merchant622', 'merchant623', 'merchant624', 'merchant625', 'merchant626', 'merchant627', 'merchant628', 'merchant629', 'merchant630', 'merchant631', 'merchant632', 'merchant633', 'merchant634', 'merchant635', 'merchant636', 'merchant637', 'merchant638', 'merchant639', 'merchant640', 'merchant641', 'merchant642', 'merchant643', 'merchant644', 'merchant645', 'merchant646', 'merchant647', 'merchant648', 'merchant649', 'merchant650', 'merchant651', 'merchant652', 'merchant653', 'merchant654', 'merchant655', 'merchant656', 'merchant657', 'merchant658', 'merchant659', 'merchant660', 'merchant661', 'merchant662', 'merchant663', 'merchant664', 'merchant665', 'merchant666', 'merchant667', 'merchant668', 'merchant669', 'merchant670', 'merchant671', 'merchant672', 'merchant673', 'merchant674', 'merchant675', 'merchant676', 'merchant677', 'merchant678', 'merchant679', 'merchant680', 'merchant681', 'merchant682', 'merchant683', 'merchant684', 'merchant685', 'merchant686', 'merchant687', 'merchant688', 'merchant689', 'merchant690', 'merchant691', 'merchant692', 'merchant693']

In [10]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_list = {"category_id":cat_ids,"category":categories}
category_df = pd.DataFrame(category_list)
# Create a job DataFrame with the job_id array as the job_id and jobs list as the job name. 
job_list = {"job_id":job_ids,"job":jobs}
job_df = pd.DataFrame(job_list)
# Create a merchant DataFrame with the merchant_id array as the merchant_id and merchant list as the merchant name. 
merchant_list = {"merchant_id":merchant_ids,"merchant":merchant}
merchant_df = pd.DataFrame(merchant_list)
# Create a city DataFrame with the city_id array as the city_id and city list as the city name. 
city_list = {"city_id":city_ids,"city":city}
city_df = pd.DataFrame(city_list)

In [11]:
category_df

   category_id        category
0         cat1   entertainment
1         cat2   gas_transport
2         cat3        misc_pos
3         cat4     food_dining
4         cat5     grocery_pos
5         cat6     grocery_net
6         cat7    shopping_pos
7         cat8        misc_net
8         cat9    shopping_net
9        cat10            home
10       cat11       kids_pets
11       cat12   personal_care
12       cat13  health_fitness
13       cat14          travel

In [12]:
job_df

     job_id                               job
0      job1           Therapist, occupational
1      job2             Forensic psychologist
2      job3     Development worker, community
3      job4                  Product designer
4      job5                 Nurse, children's
..      ...                               ...
473  job474  Production assistant, television
474  job475               Engineer, materials
475  job476     Operational investment banker
476  job477                 Software engineer
477  job478                   Engineer, water

[478 rows x 2 columns]

In [13]:
merchant_df

     merchant_id                               merchant
0      merchant1                 fraud_Kilback and Sons
1      merchant2                      fraud_Kuvalis Ltd
2      merchant3                       fraud_Herzog Ltd
3      merchant4                       fraud_Kuphal-Toy
4      merchant5                     fraud_Bauch-Raynor
..           ...                                    ...
688  merchant689      fraud_Reichel, Bradtke and Blanda
689  merchant690                      fraud_Hyatt-Blick
690  merchant691  fraud_McLaughlin, Armstrong and Koepp
691  merchant692                      fraud_Boyer-Haley
692  merchant693                 fraud_Corwin-Romaguera

[693 rows x 2 columns]

In [14]:
city_df

     city_id         city
0      city1     Waukesha
1      city2       Thomas
2      city3      Tamaroa
3      city4    Pea Ridge
4      city5   North Loup
..       ...          ...
844  city845        Craig
845  city846    Senatobia
846  city847  Springville
847  city848         Rice
848  city849      Grifton

[849 rows x 2 columns]

In [15]:
# Export categories_df and job_df as CSV files.
category_df.to_csv("category.csv", index=False)
job_df.to_csv("job.csv", index=False)

In [16]:
# Export merchant_df and city_df as CSV files.
merchant_df.to_csv("merchant.csv", index=False)
city_df.to_csv("city.csv", index=False)

###Divided Fraud DataFrame
----
**Create a FraudTest DataFrame that has the following columns:**
- The "Trans_Date" column.
- The "Trans_Time" column.
- The “merchant” column.
- The "category" column is renamed as "description."
- The "amount" column.
- The "first" column. 
- The "last" column. 
- The "gender" column. 
- The "street" column.
- The "city" column.
- The "zip" column.
- The "lat" column.
- The "long" column.
- The "city_pop" column.
- The "job" column.
- The "date_of_birth" column.
- The "merch_lat" column.
- The "merch_long" column.
Then export the DataFrame as a `FraudTestMerged.csv` CSV file.

In [17]:
FraudTest =pd.read_excel('fraudTest.xlsx')
FraudTest.head(5)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867240,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201290,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024750,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438420,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003040,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [18]:
# Rename the amt, dob.
FraudTest = FraudTest.rename(columns={'amt':'amount','dob':'date_of_birth'})
FraudTest.head(5)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amount,first,last,gender,street,...,lat,long,city_pop,job,date_of_birth,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867240,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201290,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024750,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438420,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003040,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [19]:
# Check the datatypes
FraudTest.dtypes

Unnamed: 0                        int64
trans_date_trans_time    datetime64[ns]
cc_num                            int64
merchant                         object
category                         object
amount                          float64
first                            object
last                             object
gender                           object
street                           object
city                             object
state                            object
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                              object
date_of_birth            datetime64[ns]
trans_num                        object
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

In [20]:
# Strip trans_data_trans_time column
from datetime import datetime as dt
FraudTest["fraud_date"]= FraudTest["trans_date_trans_time"].dt.date
FraudTest["fraud_time"]= FraudTest["trans_date_trans_time"].dt.time

In [21]:
# drop trans_date_trans_time column
FraudTest.drop(['trans_date_trans_time'], axis = 1, inplace = True)

In [22]:
#drop irrelevant columns
FraudTest.drop(['Unnamed: 0'], axis = 1, inplace = True)
FraudTest.drop(['cc_num'], axis = 1, inplace = True)
FraudTest.drop(['trans_num'], axis = 1, inplace = True)
FraudTest.drop(['unix_time'], axis = 1, inplace = True)
FraudTest.drop(['is_fraud'], axis = 1, inplace = True)
FraudTest.drop(['street'], axis = 1, inplace = True)
FraudTest.drop(['state'], axis = 1, inplace = True)
FraudTest.drop(['zip'], axis = 1, inplace = True)

In [23]:
FraudTest.head(5)

,merchant,category,amount,first,last,gender,city,lat,long,city_pop,job,date_of_birth,merch_lat,merch_long,fraud_date,fraud_time
0,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,Columbia,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,33.986391,-81.200714,2020-06-21,12:14:25
1,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,Altonah,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,39.450498,-109.960431,2020-06-21,12:14:33
2,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,Bellmore,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,40.495810,-74.196111,2020-06-21,12:14:53
3,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,Titusville,28.5697,-80.8191,54767,Set designer,1987-07-25,28.812398,-80.883061,2020-06-21,12:15:15
4,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,Falmouth,44.2529,-85.0170,1126,Furniture designer,1955-07-06,44.959148,-85.884734,2020-06-21,12:15:17

In [24]:
# Merge the FraudTest with the category_df on the "category" column and 
# the job_df on the "job" column.
# the city_df on the "city" column.
# the merchant_df on the "merchant" column.
Fraud_cat_df = pd.merge(FraudTest,category_df, on = 'category')
Fraud_job_df = pd.merge(Fraud_cat_df, job_df, on = 'job')
Fraud_city_df = pd.merge(Fraud_job_df, city_df, on = 'city')
FraudTest_df = pd.merge(Fraud_city_df, merchant_df, on = 'merchant')
FraudTest_df.tail(10)

,merchant,category,amount,first,last,gender,city,lat,long,city_pop,job,date_of_birth,merch_lat,merch_long,fraud_date,fraud_time,category_id,job_id,city_id,merchant_id
555709,fraud_Ankunding-Carroll,travel,481.47,Thomas,Hale,M,Cazenovia,43.4987,-90.2796,1360,Occupational hygienist,1984-11-06,43.155616,-89.830328,2020-07-28,12:42:36,cat14,job42,city186,merchant483
555710,fraud_Ankunding-Carroll,travel,6.97,Vincent,Ward,M,North Brookfield,42.2665,-72.0821,4680,Field seismologist,1986-04-03,42.779083,-72.879350,2020-06-27,19:14:18,cat14,job113,city687,merchant483
555711,fraud_Ankunding-Carroll,travel,7.38,Dale,Smith,M,Purmela,31.4841,-97.9903,258,Web designer,1943-12-15,31.444597,-97.310265,2020-11-22,15:17:27,cat14,job409,city636,merchant483
555712,fraud_Ankunding-Carroll,travel,2.60,Kendra,King,F,Smith River,41.9404,-124.1587,1930,Web designer,1983-06-13,41.604802,-124.388894,2020-12-04,13:44:48,cat14,job409,city740,merchant483
555713,fraud_Ankunding-Carroll,travel,3.83,Connor,Grant,M,Northport,40.9051,-73.3309,21902,Tour manager,1976-05-16,41.850565,-73.599376,2020-11-16,21:47:33,cat14,job368,city520,merchant483
555714,fraud_Ankunding-Carroll,travel,510.94,Jason,Hernandez,M,Hewitt,44.6437,-90.1031,828,Arts development officer,1991-08-19,44.187445,-89.664472,2020-08-02,17:24:11,cat14,job225,city277,merchant483
555715,fraud_Ankunding-Carroll,travel,2.13,Nicholas,Tran,M,Belmont,43.4512,-71.4890,7430,"Scientist, research (medical)",1955-01-13,44.407266,-71.686215,2020-12-27,17:07:12,cat14,job31,city32,merchant483
555716,fraud_Ankunding-Carroll,travel,7.60,Brenda,Johnson,F,Norwich,39.9934,-81.8024,1443,Research scientist (medical),1962-03-04,40.151992,-81.601878,2020-12-22,12:33:11,cat14,job242,city303,merchant483
555717,fraud_Ankunding-Carroll,travel,470.92,David,Vasquez,M,Parker Dam,34.2980,-114.1560,126,Marketing executive,1992-10-07,34.603725,-113.282115,2020-11-20,14:56:45,cat14,job360,city500,merchant483
555718,fraud_Ankunding-Carroll,travel,6.56,Susan,Garcia,F,Albuquerque,35.1506,-106.5690,641349,Civil Service administrator,1976-04-11,36.087054,-106.830435,2020-12-17,15:32:50,cat14,job222,city269,merchant483

In [25]:
# Export the DataFrame as a CSV file. 
FraudTest_df.to_csv("FraudTestMerged.csv", index=False)